# Generated by Django 5.2.8 on 2025-11-24 02:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('storage_path', models.CharField(max_length=500, verbose_name='مسار التخزين')),
                ('public_url', models.URLField(max_length=1000, verbose_name='الرابط العام')),
                ('file_size', models.BigIntegerField(verbose_name='حجم الملف')),
                ('content_type', models.CharField(max_length=100, verbose_name='نوع الملف')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الرفع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'ملف مرفوع',
                'verbose_name_plural': 'ملفات مرفوعة',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
